---
# Crear la estructura de directorios
- name: Crear directorios para 2do_parcial
  file:
    path: "/tmp/2do_parcial/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - alumno
    - equipo

# Crear el archivo datos_alumno.txt
- name: Crear datos_alumno.txt
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

# Crear el archivo datos_equipo.txt
- name: Crear datos_equipo.txt
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

# Configurar sudoers para el grupo 2PSupervisores
- name: Configurar sudoers para el grupo 2PSupervisores
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%2PSupervisores'
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

